# Noções básicas de fisiologia pós colheita de produtos hortícolas {#pos}

<style>
body { text-align: justify}
</style>

## Introdução

O parágrafo introdutório da publicação "**Fisiologia e Manuseio Pós-Colheita de Pimentão**" destaca que: - *O correto manuseio durante e após a colheita é importante para garantir a qualidade sensorial, nutricional e microbiológica dos alimentos assim como para reduzir as perdas. As perdas pós-colheita impactam a sustentabilidade dos sistemas agroalimentares nas três dimensões: econômica, social e ambiental. Elas reduzem a disponibilidade e aumentam o preço dos alimentos comprometendo a segurança alimentar. Elas também têm um grande impacto sobre o meio ambiente seja pelo uso em vão de recursos naturais escassos para produzir alimentos que são descartados, seja pela geração de lixo que é enviado para lixões e aterros sanitários* (HIGH LEVEL PANEL OF EXPERTS ON FOOD SECURITY AND NUTRITION,2014 *apud* [@Milza]).

Esta publicação concorda com essa abordagem, dando destaque e reproduzindo o texto da autora. Inclusive, os princípios por ela destadados e defendidos integraram os estudos para a elaboração da legislação sobre os requisitos mínimos dos produtos hortícolas, tratado no Capítulo \@ref(req).

Por possuírem características intrínsecas muito particulares, e devido a norma dos requisitos mínimos focar os aspectos que devem ser controlados para impedir a oferta de produtos não conformes ao consumidor final, destacamos a abordagem sugerida pela autora que reforça essa visão, na sequência de capítulos abaixo.

## Aspectos gerais e objetivos

Este capítulo reforça os principais fatores da fisiologia dos produtos hortícolas que impactam de forma negativa e em caráter irreversível a sua qualidade final, impedindo a oferta desses produtos ao consumidor final.

Esses fatores têm base na ciência da fisiologia da pós colheita desses produtos e devem ser o foco de qualquer ação fiscal que busque garantir a oferta de produtos hortícolas de qualidade ao consumidor final.

Apresentada na publicação da Embrapa [@Milza], a palavra **estragar**, em - "*o fruto estraga depois de colhido*", ilustra um dos alvos deste Capítulo que busca estabelecer os critérios básicos que identificam de forma clara e simples, mas com base científica sólida, os aspectos dos produtos hortícolas que impedem a sua comercialização.

O desenvolvimento de um produto hortícola caracteriza-se pelo seu crescimento na lavoura, maturação (incluída a maturidade fisiológica), amadurecimento e senescência [@WATADA]^[Explicado em: https://edisciplinas.usp.br/pluginfile.php/1913455/mod_resource/content/0/Aula%2024.08.2016%20%28grad%29%20%20-%20Desenvolvimento%20e%20Fisiologia.pdf]. 

Interessa para a fiscalização identificar os aspectos que levam de forma irreversível à senescência, estádio posterior ao amadurecimento que se caracteriza pela prevalência dos processos de morte e degradação dos tecidos celulares dos produtos hortícolas. Importa menos para a fiscalização a identificação precisa da origem da senescência, sendo mais relevante e decisivo evidenciar o caráter irreversível de **produto estragado** para o consumidor final -> objeto da ação fiscal. 




## Processos pós-colheita que levam à deterioração

Os principais aspectos da fisiologia pós-colheita dos produtos hortícolas que são irreversíveis, ou seja, **conduzirão o produto à senescência sem atingir a maturação**, e que devem ser considerados pelo responsável pelo produto hortícola, também devem ser o foco da fiscalização.

O produto nessas condições de irreversibilidade não se presta para a sua finalidade proposta, já que será considerado *estragado* pelo consumidor final antes ou, pior, após a aquisição.

Assim sendo, produtos não climatéricos (Tabela 4.1) colhidos imaturos não se prestam para o consumo, já que atingirão a senescência sem alcançar a maturação. 



```{r, include=FALSE, echo = FALSE}

library(readxl)
library(knitr)
library(kableExtra)
library(dplyr)

climat <- read_xlsx('~/R_files/02_scripts/climat.xlsx') 
climat[is.na(x=climat)] <- "--"

climat <- climat %>% select("2", "3","5", "6")
names(climat)[1]="Climatérico"
names(climat)[2]="Nome científico"
names(climat)[3]="Não Climatérico"
names(climat)[4]="Nome científico"


```

`r knitr::kable(climat, booktabs = TRUE,longtable = TRUE,
  caption = 'Listagem de produtos hortícolas Climatéricos e não climatéricos com base na taxa de respiração.'
) %>% kable_styling(font_size = 10)%>%
kable_styling(latex_options = c("striped", "scale_down"))%>%
column_spec(1, width = "2cm")%>%column_spec(2, width = "2.6cm")%>%column_spec(2, italic = T)%>%column_spec(3, width = "2cm")%>%column_spec(4, width = "2.6cm")%>%column_spec(4, italic = T)%>%
kable_styling(latex_options = c("repeat_header"))`
Adaptado de [@UNECE] e [@CALBO]

A avaliação dos sólidos solúveis totais, expresso em ºBrix é capaz de determinar se um produto hortícola não climatérico foi colocado no comércio sem ter atingido o seu grau de maturação mínimo. Os valores preconizados desse parâmetro podem ser consultados no [Referencial fotográfico de determinados produtos hortícolas](https://www.gov.br/agricultura/pt-br/assuntos/inspecao/produtos-vegetal/arquivos/referencial-fotografico/referencial-fotografico).

Outros aspectos relacionados por [@Milza], que aceleram a senescência e que podem ser considerados como fatores que caracterizam a irreversibilidade do processo de deterioração são:

* o ataque dos produtos por doenças bacterianas ou fúngicas, causadoras de podridrões; e

* os danos físicos, causadores de ferimentos que tanto aceleram a perda de água, quanto a respiração dos produtos hortícolas, acelerando o amadurecimento e,
consequentemente, reduzindo a vida útil dos produtos.

Também podemos relacionar nessa lista os danos por calor ou a exposição excessiva ao sol, além da injúria por frio, mas somente quando esses danos também  causarem ou forem associados a outros fatores de deterioração dos produtos como a perda de água, ferimentos, murcha excessiva, ruptura da casca etc, já que esses danos são de percepção variável conforme o produto. 

Sobre esse aspecto, [@UNECE] relacionou uma extensa lista de produtos hortícolas com base em sua sensibilidade às injúrias pelo frio excessivo, também identificando as temperaturas ideais para o armazenamento desses produtos.
