--- 
title: "Produtos Hortícolas: Rastreabilidade e Requisitos Mínimos"
author: "Edição: André Luiz B. Oliveira - Autores:"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Legislação explicada para cumprimento e fiscalização da legislação."
---

# Legislação Aplicável



Rastreabilidade - A INC nº 02/2018 estabelece os procedimentos para a aplicação da rastreabilidade ao longo da cadeia produtiva de produtos vegetais frescos destinados à alimentação humana, [@INC].

Requisitos Mínimos dos produtos hortícolas - A IN nº 69/2018 estabelece o Regulamento Técnico definindo os requisitos mínimos de identidade e qualidade para Produtos Hortícolas, [@REQ]. Essa norma é assistida pelo [Referencial fotográfico que ilustra os requisitos mínimos](https://www.gov.br/agricultura/pt-br/assuntos/inspecao/produtos-vegetal/arquivos/referencial-fotografico/referencial-fotografico), um conjunto de imagens que facilitam a identificação dos defeitos e condições das frutas, legumes e verduras não conformes com a IN nº 69/2018 e que devem ser removidos do mercado.

Fiscalização dos requisitos mínimos dos produtos hortícolas - A IN nº 07/2019 estabelece os procedimentos simplificados para a fiscalização de produtos hortícolas, [@FiscREQ].

Fundamentação legal - Lei e Decreto que instituem a classificação de produtos vegetais, subprodutos e resíduos de valor econômico, [@Lei], [@Decr].

```{r eval=FALSE, include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
